export const assets = [
    {name: "warrior-animations", src: "common/warrior.json"},
    {name: "MyFont", src: "common/fonts/upheavtt.ttf"},
    {name: "MyFont2", src: "common/fonts/UchronyArrows-Bold-FFP.ttf"},
    {name: "forestBackground1", src: "common/forestBackground1.png"},
    {name: "forestBackground2", src: "common/forestBackground2.png"},
    {name: "forestBackground3", src: "common/forestBackground3.png"},
    {name: "forestBackground4", src: "common/forestBackground4.png"},
    {name: "forestBackground5", src: "common/forestBackground5.png"},
    {name: "forestBackground6", src: "common/forestBackground6.png"},
    {name: "smallPlatform", src: "common/smallPlatform.png"},
    {name: "mediumPlatform", src: "common/mediumPlatform.png"},
    {name: "menu-PopUp", src: "common/menu-popup.png"},
    {name: "option-PopUp", src: "common/option-popup.png"},
    {name: "logo", src: "common/logo.png"},
    {name: "button", src: "common/button.png"},
    {name: "forest(0,0)", src: "common/level/forest/start.png"},
    {name: "forest(1,0)", src: "common/level/forest/forest(10).png"},
    {name: "forest(2,0)", src: "common/level/forest/forest(20).png"},
    {name: "forest(3,0)", src: "common/level/forest/forest(30).png"},
    {name: "forest(4,0)", src: "common/level/forest/forest(40).png"},
    {name: "forest(5,0)", src: "common/level/forest/forest(50).png"},
    {name: "forest(6,0)", src: "common/level/forest/forest(60).png"},
    {name: "title", src: "common/title.png"},
    {name: "sign", src: "common/level/forest/sign.png"},
    {name: "heart", src: "common/heart.png"}
];
